w3c/webappsec-subresource-integrity

- index.html
- spec.markdown
This addresses several nits from timeless listed in https://readable-email.org/list/public-webappsec/topic/sri-comments, per issue 6.
A comments regarding this I *didn't* change:
* Given that the intro is non-normative, I added in some links and clarifications to terms, but I don't think it's appropriate to define these formally, as that's generally reserved for normative definitions.
* The brackets are a specific normative reference form. I've cleaned up the CORS one to look a little nicer, but I don't think we can change their basic use.
* Regarding "step 4 isn't clear, please add of obtain a resource...", our replacement text is identical to the HTML5 document-metadata#concept-link-obtain step 4 wording, with the addition to "...and the integrity metadata of the request to the value of …
> Address comments from timeless

- index.html
- spec.markdown
To resolve the whitespace problem in #1, I redefined WSP in Section 2.2 as White_Space characters from the HTML 5 spec. I believe this should automatically resolve the problem in section 3.5. Please take a look, @devd @fmarier @mozfreddyb.
> Redefine WSP as White_Space characters from the HTML 5 spec.

- index.html
- spec.markdown
@mikewest pointed out that we are referring to a definition that has since been removed from the mixed content spec.
> Remove potentially secure origin

- index.html
- spec.markdown
This makes all Secure Context references non-normative and also makes Security Considerations non-normative.
> Change some normative references to non-normative

- index.bikeshed.bs
- index.bikeshed.html
Background: https://github.com/w3c/webappsec-csp/pull/85.
> attempt to write down `require-sri-for` directive as part of SRI

- index.bs
Match tokens with known tokens case-insensitively in parsing algorithm
of `require-sri-for`.
> Clarification of parsing of `require-sri-for`

- Makefile
- index.bs
- index.html
This is a fix similar to w3c/webappsec-suborigins#41. Some Bikeshed change has made it so that it is more or less necessary to put  2 spaces at the begin of all Markdown lines. I'd love at least one of @fmarier, @mozfreddyb, or @devd to confirm that this change is fine by them.
> Fix compile

- index.bs
As mentioned in #52, the hash for sha512 matches one pre-image and the sha384 is for another. This makes the example confusing, as it is about two hashes for the same script.
The example in itself is non-normative so this is more or less a cosmetic change. I assume almost nobody (kudos to @manger) would compute those themselves.
Hence, I'd just patch the editor's draft and not add this to the REC.
> Change hash value in Example 5 & 6 (fixes #52)

- index.bs
"Valid metadata" wasn't well defined, "integrity metadata" didn't contain a
grammar, and nothing says what an "alg component" is.
> Be clearer about the "parse metadata" algorithm.

- index.bs
- spec_v1.markdown
Quotes must not be escaped in inline \`code\` elements, it causes the
backslashes to appear verbatim in the final page.
***
<a href="https://pr-preview.s3.amazonaws.com/tom93/webappsec-subresource-integrity/pull/81.html" title="Last updated on May 23, 2019, 1:05 AM UTC (0316991)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/81/3aadfcc...tom93:0316991.html" title="Last updated on May 23, 2019, 1:05 AM UTC (0316991)">Diff</a>
> Fix formatting

- index.bs
I really liked the feature. :cry: 
However, we ended up unshipping in Gecko and IIRC @mikewest considered removing from Blink, so I'm making an attempt at removing `require-sri-for`.
***
<a href="https://pr-preview.s3.amazonaws.com/mozfreddyb/webappsec-subresource-integrity/pull/82.html" title="Last updated on Jul 2, 2019, 1:14 PM UTC (9931d3c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/82/6edd03a...mozfreddyb:9931d3c.html" title="Last updated on Jul 2, 2019, 1:14 PM UTC (9931d3c)">Diff</a>
> Revert `require-sri-for`

- index.bs
fix terminology Content-Encoding is an header, not a content-coding
***
<a href="https://pr-preview.s3.amazonaws.com/ioggstream/webappsec-subresource-integrity/pull/94.html" title="Last updated on Jan 15, 2021, 10:59 AM UTC (0ecf245)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/94/094d447...ioggstream:0ecf245.html" title="Last updated on Jan 15, 2021, 10:59 AM UTC (0ecf245)">Diff</a>
> typo: content-encoding

- index.bs
Fixes https://github.com/w3c/webappsec-subresource-integrity/issues/41
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/pull/96.html" title="Last updated on Feb 18, 2021, 2:05 AM UTC (3e90510)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/96/550b2d9...3e90510.html" title="Last updated on Feb 18, 2021, 2:05 AM UTC (3e90510)">Diff</a>
> Reference Fetch spec rather than CORS spec

- index.bs
- index.html
Mistakenly assumed ### corresponds to `<h3>`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/pull/98.html" title="Last updated on Feb 22, 2021, 2:26 PM UTC (a08abe4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/98/afa3d6a...a08abe4.html" title="Last updated on Feb 22, 2021, 2:26 PM UTC (a08abe4)">Diff</a>
> Editorial: correct heading level

- index.bs
- index.html
This is already tackled by "Verification of HTML document subresources" and HTML Standard (which it now references).
Closes #92.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/pull/99.html" title="Last updated on Feb 22, 2021, 2:48 PM UTC (cc7c669)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/99/62b40e8...cc7c669.html" title="Last updated on Feb 22, 2021, 2:48 PM UTC (cc7c669)">Diff</a>
> Remove text redundant with HTML

- index.bs
- index.html
Bikeshed produces invalid link element
***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/webappsec-subresource-integrity/pull/95.html" title="Last updated on Feb 22, 2021, 2:56 PM UTC (e46d479)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/95/abe7f92...nschonni:e46d479.html" title="Last updated on Feb 22, 2021, 2:56 PM UTC (e46d479)">Diff</a>
> chore: Remove quotes in URL

- index.bs
This fixes the misaligned index number found in [3.3.4 Do bytes match metadataList?](https://w3c.github.io/webappsec-subresource-integrity/#does-response-match-metadatalist). Bikeshed seems to fix it automatically, but it would be nice to fix it.
***
<a href="https://pr-preview.s3.amazonaws.com/baek9/webappsec-subresource-integrity/pull/111.html" title="Last updated on Jan 6, 2022, 11:43 PM UTC (7939ef4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/111/94f3b3e...baek9:7939ef4.html" title="Last updated on Jan 6, 2022, 11:43 PM UTC (7939ef4)">Diff</a>
> Fix a misaligned index number

- index.bs
This modifies "3.3.2 parse metadata" to parse metadata using primitives from https://infra.spec.whatwg.org/#string instead of ABNF grammar from https://w3c.github.io/webappsec-subresource-integrity/#grammardef-hash-with-options. This makes it clear that the user agent does not need to validate the base64 digest contained in the metadata. Also, since it induces fail-open for invalid metadata, the compatibility of the SRI is guaranteed in the future.
Issue number : #84
***
<a href="https://pr-preview.s3.amazonaws.com/baek9/webappsec-subresource-integrity/pull/110.html" title="Last updated on Nov 25, 2021, 4:15 PM UTC (e9121ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/110/94f3b3e...baek9:e9121ba.html" title="Last updated on Nov 25, 2021, …
> Edit 3.3.2 Parse metadata in more detail

- index.bs
This PR pulls together some small editorial updates that remove hard-coded links (thereby shifting to Infra and HTML in some places), and adjusts some variable names for future extensibility. Nothing crazy.
I've broken the changes out into a few distinct commits in the hopes that that makes this simpler to review.
WDYT, @mozfreddyb?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/pull/125.html" title="Last updated on Oct 7, 2024, 10:27 AM UTC (bbd1fee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/125/5aab13c...bbd1fee.html" title="Last updated on Oct 7, 2024, 10:27 AM UTC (bbd1fee)">Diff</a>
> Editorial updates

- .github/workflows/build-validate-publish.yml
[GitHub will no longer support the Ubuntu 20.04 runner image starting from April 1, 2025](https://github.com/actions/runner-images/issues/11101). That PR updates the actions to use ubuntu-latest instead
> GitHub actions: replace ubuntu-20.04 with ubuntu-latest

- index.bs
This PR labels the spec as "Level 2" (a formality, as we published the original under a W3C Process that doesn't allow us to update snapshotted CRs), and records editors' emeritus status.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/pull/132.html" title="Last updated on Mar 20, 2025, 8:29 AM UTC (48ac065)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/132/ac31b01...48ac065.html" title="Last updated on Mar 20, 2025, 8:29 AM UTC (48ac065)">Diff</a>
> Prepare for an FPWD of SRI2.

- index.bs
As discussed, this is replacing #129
It is defining two new headers: `Integrity-Policy` and `Integrity-Policy-Report-Only` that would enable developers to enforce integrity on scripts (in the immediate) and on more request destinations in the future.
Subresource-Integrity (SRI) enables developers to make sure the assets they intend to load are indeed the assets they are loading. But there's no current way for developers to be sure that all of their scripts are validated using SRI. 
The `Integrity-Policy` header gives developers the ability to assert that every resource of a given type needs to be integrity-checked. If a resource of that type is attempted to be loaded without integrity metadata, that attempt will fail and trigger a violation report.
The `Integrity-Policy` header is a …
> Add Integrity-Policy for scripts

- index.bs
The "should block request.." & "parse.." algorithms and the integrity policy structs should've been exported. This actually does that so that we can properly integrate with Fetch and HTML.
Beyond that, this also fixes a bug where the reportPolicy's "inline" was ignored.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/pull/134.html" title="Last updated on May 22, 2025, 8:37 AM UTC (0944bc3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/134/a7db551...0944bc3.html" title="Last updated on May 22, 2025, 8:37 AM UTC (0944bc3)">Diff</a>
> Integrity policy - export the dfns required for integration and fix a bug

- index.bs
Single quotes aren't valid JSON. This also happened to make the JSON highlighter freak out and color things in a bizarre fashion.
***
<a href="https://pr-preview.s3.amazonaws.com/tabatkins/webappsec-subresource-integrity/pull/139.html" title="Last updated on Jun 3, 2025, 10:17 PM UTC (90510fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/139/2089aeb...tabatkins:90510fb.html" title="Last updated on Jun 3, 2025, 10:17 PM UTC (90510fb)">Diff</a>
> [editorial] Make JSON valid

- index.bs
This fixes #136. Both WPT and Chrome's implementation exempt data and blob urls, the spec should probably mention this.
***
<a href="https://pr-preview.s3.amazonaws.com/FKLC/webappsec-subresource-integrity/pull/137.html" title="Last updated on Jun 4, 2025, 1:50 PM UTC (b4767bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/137/2089aeb...FKLC:b4767bf.html" title="Last updated on Jun 4, 2025, 1:50 PM UTC (b4767bf)">Diff</a>
> Add blob and data url exemption

- index.bs
Addresses the comment on https://github.com/w3c/webappsec-subresource-integrity/pull/133#issuecomment-2951224941 by adding a usage example and a minimal explanation.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/pull/142.html" title="Last updated on Jun 12, 2025, 2:41 PM UTC (5f4a4a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/142/2e039a4...5f4a4a2.html" title="Last updated on Jun 12, 2025, 2:41 PM UTC (5f4a4a2)">Diff</a>
> Integrity policy example

- index.bs
Hello!
As a next step to integrity policy, we are thinking about supporting stylesheets too. So, I'm creating this pull request to add it to the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/FKLC/webappsec-subresource-integrity/pull/146.html" title="Last updated on Jul 4, 2025, 1:18 PM UTC (87e2e96)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webappsec-subresource-integrity/146/679d685...FKLC:87e2e96.html" title="Last updated on Jul 4, 2025, 1:18 PM UTC (87e2e96)">Diff</a>
> Extend integrity policy's coverage to include stylesheets

- .github/ISSUE_TEMPLATE/0-new-issue.yml
- .github/ISSUE_TEMPLATE/1-new-feature.yml
- .github/pull_request_template.md
I allowed myself to adapt the wonderful issue & pull request templates from WHATWG, such that we can have pointers to all the interesting things (implementation bugs, wpt, standards positions etc). I believe this will help transition SRI to a living standard.
> Add issue & pull request template
